terraform-providers/terraform-provider-docker

- README.md
Changes github repositories from `hashicorp` to `terraform-providers` to be able to setup for local development.
> Fixes git paths in README to terraform-providers.

- website/docs/d/registry_image.html.markdown
- website/docs/index.html.markdown
- website/docs/r/image.html.markdown
* fixes the layout issue in https://www.terraform.io/docs/providers/docker/index.html#registry-credentials
* removes notes that only images from the public registry can be pulled, because private registries are now supported as well.
> Fixes layout and notes in docs.

- docker/resource_docker_container.go
This modification allows using the "awslogs"' log driver, in order to send logs to AWS CloudWatch Logs.
> Allow the awslogs log driver

- docker/resource_docker_container.go
- website/docs/r/container.html.markdown
Just a short note on the links feature being legacy and marked as insecure on Docker upstream.
> Adds warning about the link feature

- website/docs/r/container.html.markdown
This PR update the doc about ports which are not both required. It's relative to the issue #8 which could be closed.
> [fix-documentation-ports] only one port has to be set

- CHANGELOG.md
- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
Specifically the following issues:
Cannot be tested because the external port > 32768 is generated and so the hash of the port set changes every time: `ports.425894982.external`
```
testValueHigherEqualThan("docker_container.foo", "ports.425894982.external", "32768"),
```
> fixes ports on containers

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_network.go
- docker/resource_docker_network_funcs.go
- docker/resource_docker_network_test.go
- docker/resource_docker_secret.go
- docker/resource_docker_secret_test.go
- docker/resource_docker_volume.go
- docker/resource_docker_volume_test.go
- website/docs/r/network.html.markdown
- website/docs/r/secret.html.markdown
- website/docs/r/volume.html.markdown
This PR adds the missing labels to `docker_network` and `docker_volume` resources allowing to simulate docker-compose stacks. It can be used to support docker UCP/swarm collections.
Improvements:
- add labels to `docker_network` and these new flags: attachable, ingress, ipv6
- add labels to `docker_volume`
- add labels to `docker_secret`
- fix bug with default bridge network and custom user networks (`network_mode` + `networks`). Network aliases are working now (`network_alias`)
I use this plan to test it with portainer which have the capability to show docker stacks (swarm + docker-compose):
```
variable "docker_project" {
default = "test"
}
resource "docker_network" "default" {
name       = "${var.docker_project}_default"
attachable = true
labels {
"com.docker.compose.network" = …
```
> Add labels to support docker stacks

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
This PR adds the support of rm (autoremove) and attach options to `docker_container` resources. It can be used to run task/batch docker containers or to execute `local-exec` provisioner at the end of container execution (i.e. end of resource creation).
Options:
- `rm`: autoremove the container after his execution
- `attach`: attach to the container and wait the end of execution before reading the resource state
You can catch the container exit code with the `exit_code` attribute if you disable the `must_run` option.
```
resource "docker_image" "busybox" {
name = "busybox:latest"
}
resource "docker_container" "test" {
image   = "${docker_image.busybox.name}"
name    = "test"
restart = "no"
command  = ["/bin/sh", "-c", "exit 123"]
attach   = true
must_run = false
provisioner "local-exec" { …
```
> Add rm and attach options to execute short-lived containers

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
This PR allows to create only a container without starting it after creation (it will start at next reboot depending of the restart policy).
```
resource "docker_image" "foo" {
name = "nginx:latest"
}
resource "docker_container" "foo" {
name = "tf-test"
image = "${docker_image.foo.latest}"
start = false
must_run = false
}
```
> Add the docker container start flag

- docker/resource_docker_image_funcs.go
- docker/resource_docker_image_funcs_test.go
Adding support for missing variants of registry/foo/bar/baz and registry/foo/bar/baz:tag.
> Simplify the image options parser.

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
This PR adds the feature to retrieve the logs of a ```docker_container``` resource allowing to parse them inside the plan or to store them with a  ```local_file``` resource.  The ```attach``` option must be enabled.
Sample plan to test:
```
resource "docker_image" "busybox" {
name = "busybox:latest"
}
resource "docker_container" "test" {
image   = "${docker_image.busybox.name}"
name    = "test"
restart = "no"
command  = ["/bin/sh", "-c", "for i in $(seq 1 10); do echo \"$i\" && sleep 1; done;exit 123"]
must_run = false
attach   = true   # required
logs     = true   # enable this option to retrieve logs and save them in `container_logs`
}
resource "local_file" "logs" {
filename = "container.log"
content = "${docker_container.test.container_logs}"
}
```
```
18:49 $ cat container.log 
1
2
3 …
```
> Add container logs option

- website/docs/r/container.html.markdown
Currently at https://www.terraform.io/docs/providers/docker/r/container.html there is an incorrect indentation with the list.
> Fix incorrect indentation in docs

- website/docs/r/service.html.markdown
Fixed a typo in `service.html.markdown` file, updated `tmpf_options` to `tmpfs_options`.
> Update service.html fixed typo `tmpf_options`

- docker/provider_test.go
- docker/resource_docker_container_test.go
This allows us to skip test which would otherwise fail on platform that don't support swap limit capability.
> tests: Skip test if swap limit isn't available

- docker/resource_docker_container.go
Docker treats blank strings for an exposed port's IP as 0.0.0.0, but terraform doesn't recognise this. This leads to a mismatch when terraform checks the state against docker. This PR just normalizes empty values to be 0.0.0.0 when stored in the state so they match up.
I've manually tested this and it fixes #127. I wasn't sure how best to automate a test but if someone can point me in the right direction I'm happy to give it a go.
> Normalize blank port IP's to 0.0.0.0

- website/docs/r/config.html.markdown
- website/docs/r/container.html.markdown
- website/docs/r/secret.html.markdown
- website/docs/r/service.html.markdown
- This makes the detailed `docker_service` example run cleanly, and
standardises on `terraform fmt`ed docs so they're easy to read (some
already matched, some didn't).
Given this is mostly whitespace, reviewing with `?w=1` will make the diff smaller. :-)
> Fix syntax error in docker_service example and make all examples adhere to terraform fmt

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- docker/resource_docker_service.go
This PR ports the mounts schema to container resource schema from the docker service resource. This PR also fixes a bug that that would prevent container creation if tmpfs mounts were present. 
From https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate 
Under the `Mounts` map specification the `type` field says that `source` cannot be specified if the `type` is `tmpfs`:
>tmpfs Create a tmpfs with the given options. The mount source cannot be specified for tmpfs.
Adding a source will result in an error from the API, example from a failing test: 
>docker_container.foo_mounts: Unable to create container: Error response from daemon: invalid mount config for type "tmpfs": field Source must not be specified
> docker_container resource mounts support

- .travis.yml
- docker/resource_docker_service_funcs.go
- docker/resource_docker_service_test.go
- scripts/runAccTests.sh
Several tests run fine locally and on `travis` but not in the official CI tool which builds and releases the provider. This is the reason why several tests have to be adapted.
- pin version to `v1` on service test with private image
- fixes flaky service update test by adding retry for fetch the registry auth
> Fixes for flaky tests

- CHANGELOG.md
- docker/resource_docker_container.go
- docker/resource_docker_container_test.go
Fixes #167.
`d.GetChange` returns the same elements if all the blocks were removed, so we have to look at the values of `ports.#` also to identify if new resource should be forced. Existing logic because it creates a more accurate `plan` when existing port values are just modified.
> Fix no-op in container when all 'ports' blocks are deleted.

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
This PR adds support for configuring [namespaced kernel parameters](https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime) to `resource/docker_container`.
> Add support for sysctls

- docker/resource_docker_container_funcs.go
Fix for destroy_grace_seconds - minor bugfix to remove randomness.
I've had a crack at setting up a test for this in testacc (there is currently no test), but can't seem to work it out as I'm fairly new to golang and the terraform testing framework. In the testing framework I can get the container to go into a shutdown state, but not with the grace period set so the container seems to run forever and the test fails.
This has been manually tested with a 18000 second (5 hours) timeout. See this gist for output https://gist.github.com/laurieodgers/1441a8e9069bf9ff8b0df25dcfd7eafa
> fix for destroy_grace_seconds is not adhered to #174

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
Fixes https://github.com/terraform-providers/terraform-provider-docker/issues/164.
@mavogel - Can you please review?
> Add `shm_size' attribute for `docker_container' resource.

- website/docs/r/service.html.markdown
Remove duplicate `start_period` entry in healthcheck section of the documentation for docker_service.
> Minor docker_service documentation fix

- docker/resource_docker_service_test.go
- docker/structures_service.go
Fixes #121 by preserving the whole remaining substring even if it contains the delimiter `=`
> fix: service env truncation for multiple delimiters

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
- check out the `fix-binary-upload` branch, uncomment the [lines](https://github.com/terraform-providers/terraform-provider-docker/pull/194/files#diff-6338b0235b8cfe8182bac07219a91c40R616) of the `resource_docker_container_test.go` file and run
```sh
make testacc_setup
TF_LOG=INFO TF_ACC=1 go test -v ./docker -run ^TestAccDockerContainer_upload$ -timeout 360s
```
- you will see in the log of the test, so the properties are actually written into the state
```
upload.# = 1
upload.0.content = foo
upload.0.content_base64 = 
upload.0.executable = true
upload.0.file = /terraform/test.txt
```
- but actually the check fails:
```go
resource.Test(t, resource.TestCase{
PreCheck:  func() { testAccPreCheck(t) },
Providers: testAccProviders,
Steps: []resource.TestStep{
{
Config: …
```
> fix: binary upload as base 64 content

- docker/resource_docker_container.go
See https://docs.docker.com/config/containers/logging/configure/ section “Supported logging drivers"
Fix #204 specifically.
I don't think backward compatibility should be a concern here.
Worse case scenario, someone tries to use a missing logging driver with an older docker version, and docker will error out.
The provider should not be in the business of managing errors instead of docker. I would even go one step further and suggest this provider removes the whitelist entirely (allowing people who use third-party logging plugin to use it).
Ping @davidjameshowell @mavogel
> Updated logdrivers list

- docker/resource_docker_container.go
- docker/resource_docker_service.go
See #207 for discussion and fixes #208
@mavogel I did a search on `validateStringMatchesPattern` for other "whitelists".  The rest seems OK to  me to keep (as they are less likely to change), but then wdyt?
> Remove logging drivers white-list

- website/docs/r/service.html.markdown
Correct block is `mounts`, not `mount`
> Correct mounts block name in docs

- docker/resource_docker_service.go
- docker/validators.go
**CAUTION:** This PR will silently conflict with https://github.com/terraform-providers/terraform-provider-docker/pull/217.
That is, once _both_ of these have been merged, git will not detect any conflict but it will migrate the `0 ~> 1` change contained here to the V0 version of the resource schema, where it will not have any affect. Whichever of these two PRs is merged first, the other will need to be modified before it can be merged.
This may also be the case with any number of other PRs affecting the resources that were versioned in #217.
Implementing feature request #221.
> allow zero replicas

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
https://github.com/terraform-providers/terraform-provider-docker/issues/219
* import some docker_container's attributes. Please see docker/resource_docker_container_funcs.go
* set `Computed: true` to some attributes
* hostname
* command
* entrypoint
* env
* labels
* shm_size
* ipc_mode
* set `DiffSuppressFunc` to some attributes
* network_mode
* restart
* format by gofmt
I share verification codes.
main.tf
```hcl
provider "docker" {
}
resource "docker_image" "alpine" {
name = "alpine:3.10.3"
}
resource "docker_container" "foo" {
image       = docker_image.alpine.latest
name        = "foo"
rm          = true
entrypoint  = ["tail"]
start       = true
command     = ["-f", "/dev/null"]
read_only   = true
shm_size    = 64 # 64MB
privileged  = true
user        = "root"
working_dir = …
```
> support to import some docker_container's attributes

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
This depends on https://github.com/terraform-providers/terraform-provider-docker/pull/234
Support to update `docker_container`
* https://docs.docker.com/engine/api/v1.40/#operation/ContainerUpdate
* https://godoc.org/github.com/docker/docker/client#Client.ContainerUpdate
When the following attributes are updated, the container will be update without recreation.
* restart
* max_retry_count
* cpu_shares
* memory
* cpu_set
* memory_swap
https://github.com/terraform-providers/terraform-provider-docker/issues/237
https://github.com/terraform-providers/terraform-provider-docker/pull/234#issuecomment-572841809
> Support to update docker_container

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- scripts/testacc_cleanup.sh
- scripts/testacc_setup.sh
- website/docs/r/container.html.markdown
This fixes https://github.com/terraform-providers/terraform-provider-docker/issues/239 by allowing the use of just a filename, rather than the content of a file to be loaded into a container. Apparently anything over 4mb will cause an rpc failure in terraform as of 0.12 (or at least that's what I think I read in the codebase)
Note that I am hardly a Golang expert, and muddled through the best I could.
> Allow use of `source` file instead of content / content_base64

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
https://github.com/terraform-providers/terraform-provider-docker/issues/242
https://github.com/terraform-providers/terraform-provider-docker/issues/270
These bugs are due to https://github.com/terraform-providers/terraform-provider-docker/pull/234 .
* `Computed: true`
* env
* labels
* working_dir
* command
* entrypoint
* user
* log_opts
* log_driver
* dns
* dns_opts
* dns_search
* Stop to read the attribute
* env
* labels
The environment variables and labels are taken over from the Docker image and it causes unexpected force replacement.
Probably we don't expect to manage such environment variables and labels with Terraform,
so we shouldn't import env and labels.
> Prevent force recreate of container about some attributes

- docker/resource_docker_container.go
- docker/resource_docker_container_v1.go
#242 
https://github.com/terraform-providers/terraform-provider-docker/pull/269#issuecomment-640697737
In #269, I set `Computed: true` to some attributes to prevent the force recreation.
But I accidentaly updated not `resourceDockerContainer` but `resourceDockerContainerV1` for the following attributes.
* dns
* dns_opts
* working_dir
---
So I set `Computed: true` to these attributes of `resourceDockerContainer`.
And I separate files of `resourceDockerContainer` and `resourceDockerContainerV1` to avoid such a miss.
Sometimes we search a word in the file and jump to the matched line and fix code.
In that case, if `resourceDockerContainer` and `resourceDockerContainerV1` are in the same file,
when we jump to the line we assume the line is in `resourceDockerContainer` but sometimes actually …
> Set `Computed: true` and separate files of resourceDockerContainerV1

- website/docs/r/container.html.markdown
Fixed title and link of "Networks advanced" paragraph
> Typo in container.html.markdown

- docker/label_migration.go
- docker/resource_docker_container.go
Closes #264 
=> https://github.com/terraform-providers/terraform-provider-docker/issues/264#issuecomment-640154237
If "mounts" isn't set in Terraform Configuration with Docker provider v2.6.0,
"mounts" isn't set in State.
So `rawState` doesn't have the key "mounts" and `rawState["mounts"].([]interface{})` occurs panic.
> Fix panic to migrate schema of docker_container from v1 to v2

- docker/provider.go
- docker/provider_test.go
Having an incomplete auth config is a valid case because the auth config may depend on resources which are created after the provider. Then the provider should ignore incomplete configurations.
The current implementation fails early and prevents the deployment of all resources if the auth config is incomplete.
#250
> Prevent provider error if auth config is incomplete

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
Docker IPv6 addresses can be set automatically, provided the Docker
network in use is set up for it. In this situation, it can be useful to
be able to access the IPv6 properties as attributes.
Resolves https://github.com/terraform-providers/terraform-provider-docker/issues/265
> feat: Expose IPv6 properties as attributes

- website/docs/r/container.html.markdown
Hello maintainers! 👋 
This PR fixes a link in the `docker_container` resource. 
(I'm using standard Markdown syntax, as seen with other links in this repository)
> updates link syntax

- docker/resource_docker_container.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_test.go
- website/docs/r/container.html.markdown
This is to implement the same functionality as just issuing a `docker run --init ...`.
I think I got all the required places here but please let me know if I missed something.
> Add support for init process injection for containers.
