vendor/github.com/fsouza/go-dockerclient/Gopkg.toml
vendor/github.com/fsouza/go-dockerclient/Makefile
vendor/github.com/fsouza/go-dockerclient/client.go
vendor/github.com/fsouza/go-dockerclient/container.go
vendor/github.com/fsouza/go-dockerclient/volume.go
vendor/vendor.json

* to support the forceful removal of volumes https://github.com/fsouza/go-dockerclient/commit/5ae6bb030dd6bc294897b3b82044192b62e2a92e
* adding driver options to volume https://github.com/fsouza/go-dockerclient/commit/ed5fc0b6da049faaa72eb5b6e68b4841017ca9a1

Updated dockerclient to bf3bc17bb

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

Add support to attach devices to containers

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

Add ability to upload executable files

Add ability to upload executable files

---

CHANGELOG.md
docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

implements #88 which came originally from #17

Adds pid and namespace mode

---

CHANGELOG.md
docker/resource_docker_image_funcs.go
docker/resource_docker_image_test.go
website/docs/r/image.html.markdown

Image can be pulled with its repo digest

---

CHANGELOG.md
docker/resource_docker_container.go
docker/resource_docker_container_test.go

Documentation and external port code conflicted, so aligned the default value with documentation.

docker_container external port default value aligned with documentation

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
website/docs/r/container.html.markdown

I need to get the ip address of the containers I create on a given network.
It may be related to issue #9 .

Add ip address of each network to the computed attributes

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

Add healthcheck to `docker_container` resource.
Signed-off-by: Boris HUISGEN <bhuisgen@hbis.fr>

Add container healthcheck

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
website/docs/r/container.html.markdown

Allow to set `cpuset` to containers.

Cpuset added to containers

---

scripts/testing/Dockerfile
scripts/testing/Dockerfile_v1
scripts/testing/Dockerfile_v2
scripts/testing/Dockerfile_v3
scripts/testing/setup_private_registry.bat
scripts/testing/setup_private_registry.sh

This PR simplifies the test setup from 3 very similar Dockerfiles to one parametrized.

tests: Simplify Dockerfile(s)

---

docker/config.go
examples/ssh-protocol/README.md
examples/ssh-protocol/main.tf
go.mod
go.sum
vendor/github.com/docker/cli/AUTHORS
vendor/github.com/docker/cli/LICENSE
vendor/github.com/docker/cli/NOTICE
vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/pdeathsig_linux.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/pdeathsig_nolinux.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/session_unix.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/session_windows.go
vendor/github.com/docker/cli/cli/connhelper/connhelper.go
vendor/github.com/docker/cli/cli/connhelper/ssh/ssh.go
vendor/modules.txt

A copy of #113 with already updated and pinned dependencies for docker

Add ssh protocol (copy)

---

docker/data_source_docker_network.go
docker/data_source_docker_network_test.go
docker/provider.go
website/docs/d/docker_network.html.markdown

Singular docker_network data source

docker_network data source

---

docker/provider.go

Support for MacOS was added in terraform-providers/terraform-provider-docker#143
Here it is extended to other OSes in a generic way.
Tested on Linux with Gnome keychain (docker-credential-secretservice).

Added cross-platform support for generic Docker credential helper.

---

website/docs/r/container.html.markdown

fix website typo / containers / mount vs mounts

---

website/docs/index.html.markdown
website/docs/r/container.html.markdown

Updates the docs

---

website/docs/r/container.html.markdown
website/docs/r/network.html.markdown
website/docs/r/service.html.markdown

docs: update anchors with -1 suffix

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

PR in favor of stale #118. Adds container working dir overwrite. Closes #146

feat: adds container working dir

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

feat: adds container ipc mode.

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

Proposal to fix #191
I'm using this change right now.
Added some tests and minimal documentation.
Let me know if this patch needs to be changed / adjusted.

Support for group-add

---

docker/data_source_docker_registry_image.go
docker/data_source_docker_registry_image_test.go

Closes #186.
As outlined in #186, `docker_registry_image` fails to read from an AWS ECR registry due to the fact that the response from `GET /v2/<name>/manifests/<reference>` is lacking the header `Docker-Content-Digest` containing the digest of the response's body.
This PR fixes this issue by calculating the SHA256 digest if and only if the header is missing. I added a couple of unit tests around this while avoiding, for the time being, to add an acceptance test.

Allow docker_registry_image to read from AWS ECR registry

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

Add support for readonly containers

---

docker/provider.go
docker/resource_docker_image_test.go
website/docs/index.html.markdown

Implements the feature of #224

feat: adds config file content as plain string

---

docker/data_source_docker_network.go
docker/data_source_docker_network_test.go

When I wanted to use data source network, I faced an issue with the reading of IPAM configuration to terraform, this PR intends to fix this issue and test it.

Correct IPAM config read on the data provider

---

.travis.yml
docker/resource_docker_service_funcs.go

https://github.com/terraform-providers/terraform-provider-docker/issues/237
This issue can't be reproduced at localhost.
I want to run test with debug option.

Debug issue 237

---

.travis.yml

- Docker `19.03`
- ubuntu `bionic`

ci: bumps docker and ubuntu

---

docker/resource_docker_container.go

While comparing ports from the state with the new plan, it would sometimes compare 2 port objects with the same internal ports but different protocols, even though there is a port object with the same internal port and the same internal protocol, but it's just further down the list. 
And thus it would trigger a replacement.
Pretty consistent reproducing rate by adding these ports.
```
ports {
internal = 8300
external = 8300
protocol = "tcp"
}
ports {
internal = 8301
external = 8301
protocol = "tcp"
}
ports {
internal = 8301
external = 8301
protocol = "udp"
}
ports {
internal = 8302
external = 8302
protocol = "tcp"
}
ports {
internal = 8302
external = 8302
protocol = "udp"
}
ports {
internal = 8500
external = 8500
protocol = "tcp"
}
ports {
internal = 8600
external = 8600
protocol = "tcp" …
```

Fix port objects with the same internal port but different protocol trigger recreation of container

---

.gitignore
docker/provider.go
docker/resource_docker_registry_image.go
docker/resource_docker_registry_image_funcs.go
docker/resource_docker_registry_image_funcs_test.go
go.mod
scripts/testacc_setup.sh
scripts/testing/docker_registry_image_context/Dockerfile
website/docker.erb
website/docs/r/registry_image.html.markdown

Implementation proposal to add a new resource called docker_registry_image
See open ticket at #248

Add new resource docker_registry_image

---

docker/resource_docker_container_funcs.go

Resolve #255 by conditionally adding port binding
Set external = 0 to assign a random external port

Resolve #255 by conditionally adding port binding

---

website/docs/index.html.markdown
website/docs/r/config.html.markdown
website/docs/r/container.html.markdown

Hello maintainers 👋!
This PR updates a few things in the docs to make them more consistent.

documentation updates

---

docker/resource_docker_container.go
docker/resource_docker_container_funcs.go
docker/resource_docker_container_test.go
website/docs/r/container.html.markdown

Resolves https://github.com/terraform-providers/terraform-provider-docker/issues/288

Add security_opts to container config.

---

docker/resource_docker_container.go

Treat null workdir as a no-op

---

docker/resource_docker_container.go

Treat null user as a no-op

---

docker/data_source_docker_registry_image.go
docker/resource_docker_registry_image_funcs.go

Fix #315 
cc @mavogel 
For reference: https://github.com/opencontainers/image-spec/blob/master/manifest.md

Add support for OCI manifests
